# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('gsm_file', models.TextField()),
                ('wcdma_file', models.TextField()),
                ('lte_file', models.TextField()),
                ('rnd_gsm_file', models.TextField()),
                ('rnd_wcdma_file', models.TextField()),
                ('rnd_lte_file', models.TextField()),
                ('gsm_color', models.TextField()),
                ('wcdma_color', models.TextField()),
                ('lte_color', models.TextField()),
                ('element_color', models.TextField()),
                ('gsm_radius', models.TextField()),
                ('wcdma_radius', models.TextField()),
                ('lte_radius', models.TextField()),
                ('map_center', models.TextField()),
                ('map_zoom', models.TextField()),
                ('current_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
