# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('param', models.TextField()),
                ('value', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='CNATemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('columns', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTestLegend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.TextField()),
                ('min_value', models.TextField()),
                ('max_value', models.TextField()),
                ('color', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('table', models.TextField()),
                ('excel_file', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('tables', models.TextField(blank=True)),
                ('excel_filename', models.TextField(blank=True)),
                ('archive', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('vendor', models.TextField()),
                ('network', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FileTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField()),
                ('tasks', models.TextField()),
                ('max_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GsmGsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellSource', models.TextField()),
                ('cellTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='GsmLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellSource', models.TextField()),
                ('rncTarget', models.TextField()),
                ('utrancellTarget', models.TextField()),
                ('carrierTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='GsmWcdma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellSource', models.TextField()),
                ('rncTarget', models.TextField()),
                ('utrancellTarget', models.TextField()),
                ('carrierTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_from', models.TextField()),
                ('carrier_from', models.TextField()),
                ('symmetry', models.TextField()),
                ('technology_to', models.TextField()),
                ('carrier_to', models.TextField()),
                ('ho_realtion', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LteGsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rncSource', models.TextField()),
                ('utrancellSource', models.TextField()),
                ('carrierSource', models.TextField()),
                ('cellTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LteLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rncSource', models.TextField()),
                ('utrancellSource', models.TextField()),
                ('carrierSource', models.TextField()),
                ('rncTarget', models.TextField()),
                ('utrancellTarget', models.TextField()),
                ('carrierTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SuperFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('files', models.TextField()),
                ('network', models.TextField()),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('vendor', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vendor', models.TextField()),
                ('network', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WcdmaGsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rncSource', models.TextField()),
                ('utrancellSource', models.TextField()),
                ('carrierSource', models.TextField()),
                ('cellTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WcdmaLte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rncSource', models.TextField()),
                ('utrancellSource', models.TextField()),
                ('carrierSource', models.TextField()),
                ('rncTarget', models.TextField()),
                ('utrancellTarget', models.TextField()),
                ('carrierTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WcdmaWcdma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rncSource', models.TextField()),
                ('utrancellSource', models.TextField()),
                ('carrierSource', models.TextField()),
                ('rncTarget', models.TextField()),
                ('utrancellTarget', models.TextField()),
                ('carrierTarget', models.TextField()),
                ('status', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WNCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('cell_name', models.TextField()),
                ('nb_cell_name', models.TextField()),
                ('sc', models.FloatField(default=0)),
                ('events', models.FloatField(default=0)),
                ('drop', models.FloatField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
